[package]
name = "extract"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.3.19", features = ["derive"] }
noodles = { version = "0.47.0", features = ["fasta", "core"] }
